// chris 071415

package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"strings"
	"unicode"


	"go/ast"
	"go/parser"
	"go/token"
	"unicode/utf8"
)

// Program name.  Set by init.
var prog string

func validator(name string, s *ast.StructType) {
	first, _ := utf8.DecodeRune([]byte(name))
	isPublic := unicode.IsUpper(first)
	var fname string
	if isPublic {
		fname = fmt.Sprintf("Validate%s", name)
	} else {
		fname = fmt.Sprintf("validate%s", strings.Title(name))
	}

	fmt.Printf("func %s(data map[string]string) *%s {\n", fname, name)

	for _, fld := range s.Fields.List {
		nam := fld.Names[0].Name
		typ := fld.Type.(*ast.Ident)
		fmt.Printf("\t// %s %s\n", nam, typ)
	}

	fmt.Print("\treturn nil\n")
	fmt.Print("}\n")
}

func parse(filename string) error {
	file, err := os.Open(filename)
	if err != nil {
		return err
	}
	defer func() {
		err := file.Close()
		if err != nil {
			log.Print(err)
		}
	}()

	// Parse first before outputting anything.
	astfile, err := parser.ParseFile(token.NewFileSet(), filename, file, 0)
	if err != nil {
		return err
	}

	// Output header comment.
	progUpper := strings.ToUpper(prog)
	fmt.Printf("// *** GENERATED BY %s; DO NOT EDIT ***\n\n", progUpper)

	// Next, output original file.
	_, err = file.Seek(0, 0)
	if err != nil {
		return err
	}
	_, err = io.Copy(os.Stdout, file)
	if err != nil {
		return err
	}

	// Newline to separate things.
	fmt.Println()

	// Isolate the struct types--the things for which we want to
	// generate validator functions.
	for _, obj := range astfile.Scope.Objects {
		if obj.Kind != ast.Typ {
			continue
		}
		ts, ok := obj.Decl.(*ast.TypeSpec)
		if !ok {
			continue
		}
		s, ok := ts.Type.(*ast.StructType)
		if !ok {
			continue
		}
		if s.Fields == nil {
			return fmt.Errorf("type %s struct has empty field list %v", ts.Name, ts)
		}

		// Ok, we isolated the struct type, now output a
		// validator for it.
		validator(ts.Name.Name, s)
	}

	return nil
}

func usage() {
	log.Printf("usage: %s file.v", path.Base(os.Args[0]))
	os.Exit(2)
}

func init() {
	log.SetFlags(0)
	prog = path.Base(os.Args[0])
}

func main() {
	if len(os.Args) != 2 {
		usage()
	}

	filename := os.Args[1]
	if filename == "" {
		usage()
	}

	err := parse(filename)
	if err != nil {
		log.Fatal(err)
	}
}
